# Generated by Codex on 2026-06-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("sales", "0002_sale_payments_and_alterations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomeentry",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="income_entries",
                to="sales.sale",
            ),
        ),
    ]
