# Generated by Codex on 2026-06-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("finance", "0002_incomeentry_sale_foreignkey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashRegisterCut",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("expected_cash", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("expected_card", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("expected_transfer", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("expected_other", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("expected_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("counted_cash", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("cash_difference", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="branches.branch")),
                ("income_entries", models.ManyToManyField(blank=True, related_name="cash_cuts", to="finance.incomeentry")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cashregistercut",
            index=models.Index(fields=["branch", "date"], name="cash_cut_branch_date_idx"),
        ),
    ]
