# Generated by Codex on 2026-06-16

from django.db import migrations, models


def backfill_income_payment_details(apps, schema_editor):
    IncomeEntry = apps.get_model("finance", "IncomeEntry")
    for income in IncomeEntry.objects.select_related("sale"):
        if income.sale_id:
            income.payment_method = income.sale.payment_method
            income.cash_received = income.sale.cash_received
            income.change_due = income.sale.change_due
        else:
            income.payment_method = "OTHER"
            income.cash_received = 0
            income.change_due = 0
        income.save(update_fields=["payment_method", "cash_received", "change_due"])


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_cashregistercut"),
        ("sales", "0003_sale_payment_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomeentry",
            name="cash_received",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="incomeentry",
            name="change_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="incomeentry",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CARD", "Tarjeta"),
                    ("TRANSFER", "Transferencia"),
                    ("OTHER", "Otro"),
                ],
                default="CASH",
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_income_payment_details, migrations.RunPython.noop),
    ]
