# Generated by Codex on 2026-06-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("finance", "0004_incomeentry_payment_details"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashRegisterSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("OPEN", "Abierta"), ("CLOSED", "Cerrada"), ("CANCELLED", "Cancelada")], default="OPEN", max_length=16)),
                ("opened_at", models.DateTimeField()),
                ("opening_cash", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("expected_cash", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("expected_card", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("expected_transfer", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("expected_other", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("expected_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("counted_cash", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("cash_difference", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="branches.branch")),
                ("closed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="closed_cash_sessions", to=settings.AUTH_USER_MODEL)),
                ("opened_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="opened_cash_sessions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-opened_at"]},
        ),
        migrations.AddField(
            model_name="incomeentry",
            name="cash_session",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="income_entries", to="finance.cashregistersession"),
        ),
        migrations.CreateModel(
            name="CashDrawerMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("movement_type", models.CharField(choices=[("OPENING", "Fondo inicial"), ("IN", "Entrada"), ("OUT", "Salida"), ("WITHDRAWAL", "Retiro"), ("EXPENSE", "Gasto de caja"), ("ADJUSTMENT", "Ajuste")], max_length=16)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("concept", models.CharField(max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("cash_session", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="finance.cashregistersession")),
                ("expense", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cash_movements", to="finance.expense")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="cashregistersession",
            index=models.Index(fields=["branch", "status", "opened_at"], name="cash_session_branch_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="cashregistersession",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "OPEN")), fields=("branch",), name="unique_open_cash_session_per_branch"),
        ),
    ]
