# Generated by Django 5.1.4 on 2026-06-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='external_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/'),
        ),
    ]
