# Generated by Django 5.1.4 on 2026-06-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('ACCOUNTANT', 'Contador'), ('STORE_ADMIN', 'Administrador de tienda'), ('COLLABORATOR', 'Colaborador')], max_length=24)),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('catalog', 'Catalogo'), ('branches', 'Sucursales'), ('inventory', 'Inventario'), ('sales', 'Ventas'), ('customers', 'Clientes'), ('finance', 'Finanzas'), ('cms', 'CMS'), ('reports', 'Reportes'), ('users', 'Usuarios y permisos')], max_length=32)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['role', 'module'],
                'constraints': [models.UniqueConstraint(fields=('role', 'module'), name='unique_permission_per_role_module')],
            },
        ),
    ]
