# Generated by Django 5.1.4 on 2026-06-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('responsible_person', models.CharField(blank=True, max_length=120)),
                ('hours', models.CharField(blank=True, max_length=160)),
                ('image', models.ImageField(blank=True, upload_to='branches/')),
                ('maps_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
