# Generated by Codex on 2026-06-16

from django.db import migrations, models


def backfill_paid_amounts(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    for sale in Sale.objects.all():
        sale.amount_paid = sale.total
        sale.balance_due = 0
        sale.save(update_fields=["amount_paid", "balance_due"])


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="sale",
            name="balance_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "Pagada"),
                    ("PARTIAL", "Pago parcial"),
                    ("CANCELLED", "Cancelada"),
                    ("RETURNED", "Devuelta"),
                ],
                default="PAID",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="saleline",
            name="alteration_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="saleline",
            name="alteration_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="saleline",
            name="alteration_status",
            field=models.CharField(
                choices=[
                    ("NONE", "Sin compostura"),
                    ("WORKSHOP", "En taller"),
                    ("READY", "Lista para entregar"),
                    ("DELIVERED", "Entregada"),
                ],
                default="NONE",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="saleline",
            name="requires_alteration",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_paid_amounts, migrations.RunPython.noop),
    ]
