# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_sale_payments_and_alterations"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="cash_received",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="sale",
            name="change_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CARD", "Tarjeta"),
                    ("TRANSFER", "Transferencia"),
                    ("OTHER", "Otro"),
                ],
                default="CASH",
                max_length=16,
            ),
        ),
    ]
