# Generated by Codex on 2026-06-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_cashregistersession_cashdrawermovement_and_more"),
        ("sales", "0003_sale_payment_details"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalePayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_method", models.CharField(choices=[("CASH", "Efectivo"), ("CARD", "Tarjeta"), ("TRANSFER", "Transferencia"), ("OTHER", "Otro")], max_length=16)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cash_received", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("change_due", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cash_session", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sale_payments", to="finance.cashregistersession")),
                ("income_entry", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sale_payment", to="finance.incomeentry")),
                ("sale", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="sales.sale")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
    ]
