# Generated by Codex on 2026-06-16

from decimal import Decimal

from django.db import migrations
from django.db.models import Sum
from django.utils import timezone


def backfill_pos(apps, schema_editor):
    IncomeEntry = apps.get_model("finance", "IncomeEntry")
    CashRegisterSession = apps.get_model("finance", "CashRegisterSession")
    CashDrawerMovement = apps.get_model("finance", "CashDrawerMovement")
    SalePayment = apps.get_model("sales", "SalePayment")

    sessions = {}
    for income in IncomeEntry.objects.select_related("branch", "sale").order_by("date", "id"):
        key = (income.branch_id, income.date)
        if key not in sessions:
            opened_at = timezone.make_aware(timezone.datetime.combine(income.date, timezone.datetime.min.time()))
            session = CashRegisterSession.objects.create(
                branch_id=income.branch_id,
                status="CLOSED",
                opened_at=opened_at,
                closed_at=opened_at,
                opening_cash=Decimal("0"),
                notes="Caja historica generada por migracion.",
            )
            CashDrawerMovement.objects.create(
                cash_session=session,
                movement_type="OPENING",
                amount=Decimal("0"),
                concept="Fondo inicial historico",
            )
            sessions[key] = session
        session = sessions[key]
        income.cash_session = session
        income.save(update_fields=["cash_session"])
        if income.sale_id and not SalePayment.objects.filter(income_entry=income).exists():
            SalePayment.objects.create(
                sale_id=income.sale_id,
                cash_session=session,
                income_entry=income,
                payment_method=income.payment_method,
                amount=income.amount,
                cash_received=income.cash_received,
                change_due=income.change_due,
            )

    for session in sessions.values():
        incomes = session.income_entries.all()
        session.expected_cash = incomes.filter(payment_method="CASH").aggregate(total=Sum("amount"))["total"] or Decimal("0")
        session.expected_card = incomes.filter(payment_method="CARD").aggregate(total=Sum("amount"))["total"] or Decimal("0")
        session.expected_transfer = incomes.filter(payment_method="TRANSFER").aggregate(total=Sum("amount"))["total"] or Decimal("0")
        session.expected_other = incomes.filter(payment_method="OTHER").aggregate(total=Sum("amount"))["total"] or Decimal("0")
        session.expected_total = session.expected_cash + session.expected_card + session.expected_transfer + session.expected_other
        session.counted_cash = session.expected_cash
        session.cash_difference = Decimal("0")
        session.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_salepayment"),
        ("finance", "0005_cashregistersession_cashdrawermovement_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_pos, migrations.RunPython.noop),
    ]
